# coding: utf-8

"""
    booklooker REST API

    <p>   Die <strong>Booklooker REST API</strong> ermöglicht die sichere und einfache Kommunikation mit verschiedenen   Booklooker-Schnittstellen. Es besteht die Möglichkeit, Artikel und Aufträge abzufragen, zu ändern, zu stornieren   etc. Auch der automatische Import neuer oder geänderter Artikel ist ohne Weiteres möglich. </p> <p>   Diese API basiert auf REST. Zur Benutzung führen Sie bitte die folgenden Schritte durch: </p> <ol>   <li>     Sie benötigen Ihren persönlichen <strong>API Key</strong>, diesen erhalten Sie im Bereich     <a href=\"https://www.booklooker.de/app/priv/api_key.php\">Persönliche Daten</a>   </li>   <li>     Benutzen Sie anschließend die Schnittstelle     <a href=\"https://www.booklooker.de/pages/api_authenticate.php\">authenticate</a>     via HTTP&nbsp;POST und Sie erhalten einen <strong>Token</strong>,     welcher für alle folgenden Aufrufe benötigt wird.     Sofern Sie 10&nbsp;Minuten keine Schnittstelle aufrufen,     verfällt der Token und Sie müssen sich erneut authentifizieren.   </li>   <li>     Verwenden Sie eine der unten aufgelisteten Schnittstellen.     Die Beschreibung jeder Schnittstelle enthält die benötigten Parameter und die möglichen Rückgabewerte.   </li> </ol> <p>   Zur Kommunikation können verschiedene Programmiersprachen zum Einsatz kommen. Wir stellen Ihnen hier ein   <a href=\"https://www.booklooker.de/pages/rest_api.php?do=download&filename=booklooker_rest_api.php&path=booklooker_rest_api.php\">Beispiel in PHP</a>   zur Verfügung. </p> <p>   Weiterhin bieten wir hier eine <a href=\"https://www.booklooker.de/download/openapi.yaml\">OpenAPI Spezifikation</a> an.  </p> 

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="booklooker REST API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "booklooker REST API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    &lt;p&gt;   Die &lt;strong&gt;Booklooker REST API&lt;/strong&gt; ermöglicht die sichere und einfache Kommunikation mit verschiedenen   Booklooker-Schnittstellen. Es besteht die Möglichkeit, Artikel und Aufträge abzufragen, zu ändern, zu stornieren   etc. Auch der automatische Import neuer oder geänderter Artikel ist ohne Weiteres möglich. &lt;/p&gt; &lt;p&gt;   Diese API basiert auf REST. Zur Benutzung führen Sie bitte die folgenden Schritte durch: &lt;/p&gt; &lt;ol&gt;   &lt;li&gt;     Sie benötigen Ihren persönlichen &lt;strong&gt;API Key&lt;/strong&gt;, diesen erhalten Sie im Bereich     &lt;a href&#x3D;\&quot;https://www.booklooker.de/app/priv/api_key.php\&quot;&gt;Persönliche Daten&lt;/a&gt;   &lt;/li&gt;   &lt;li&gt;     Benutzen Sie anschließend die Schnittstelle     &lt;a href&#x3D;\&quot;https://www.booklooker.de/pages/api_authenticate.php\&quot;&gt;authenticate&lt;/a&gt;     via HTTP&amp;nbsp;POST und Sie erhalten einen &lt;strong&gt;Token&lt;/strong&gt;,     welcher für alle folgenden Aufrufe benötigt wird.     Sofern Sie 10&amp;nbsp;Minuten keine Schnittstelle aufrufen,     verfällt der Token und Sie müssen sich erneut authentifizieren.   &lt;/li&gt;   &lt;li&gt;     Verwenden Sie eine der unten aufgelisteten Schnittstellen.     Die Beschreibung jeder Schnittstelle enthält die benötigten Parameter und die möglichen Rückgabewerte.   &lt;/li&gt; &lt;/ol&gt; &lt;p&gt;   Zur Kommunikation können verschiedene Programmiersprachen zum Einsatz kommen. Wir stellen Ihnen hier ein   &lt;a href&#x3D;\&quot;https://www.booklooker.de/pages/rest_api.php?do&#x3D;download&amp;filename&#x3D;booklooker_rest_api.php&amp;path&#x3D;booklooker_rest_api.php\&quot;&gt;Beispiel in PHP&lt;/a&gt;   zur Verfügung. &lt;/p&gt; &lt;p&gt;   Weiterhin bieten wir hier eine &lt;a href&#x3D;\&quot;https://www.booklooker.de/download/openapi.yaml\&quot;&gt;OpenAPI Spezifikation&lt;/a&gt; an.  &lt;/p&gt; 
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)
